### ISSUE TITLE
Loading conftest fails (likely pytest version issue)

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-protocol-test-suite#32]
I suspect this is a version issue as this works with pytest version 4.6.3.
[stacktrace.txt](https://github.com/hyperledger/aries-protocol-test-suite/files/4344456/stacktrace.txt)

**Comment by smithbk** [comment]
Yes, I hit the same thing.  I have the fix and will open a PR

**Comment by smithbk** [comment]
@dbluhm Daniel, this should have been fixed.  Could you retest and close this if it is fixed?

**Comment by smithbk** [comment]
I'm going to go ahead and close since it is so old.  Please reopen if needed.
