### ISSUE TITLE
Officially deprecate and archive this project?

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-protocol-test-suite#46]
The last commit on this project was in February 2021. Generally speaking, there has been more interest in testing an agent against another agent using the Aries Agent Test Harness rather than testing an agent against this project. As a result, this project has seen a lack of interest or contributions for some time. As one of the original authors, I think it's time to officially deprecate and archive this project.

@ryjones @swcurran @smithbk @TelegramSam @dhh1128

**Comment by swcurran** [comment]
Agreed.

**Comment by dhh1128** [comment]
No objection from me.
