### ISSUE TITLE
publish test results in standard data structure

### ISSUE THREAD

**Issue by dhh1128** [hyperledger/aries-protocol-test-suite#9]
Would like to use a data structure like this one: https://github.com/hyperledger/indy-hipe/tree/master/text/0015-agent-test-suite-interface#interop-profile-json

[This PR](https://github.com/hyperledger/aries-rfcs/pull/220) against the aries-rfcs repo calls for implementations to formally publish test results; I'd like this data structure to be the embodiment of what's published. That is, a hyperlink to a JSON file containing this structure should be how Aries RFC implementations report their interoperability.

It might also be nice (but is less important) for this data structure to be returned as part of the [`disclose` message](https://github.com/hyperledger/aries-rfcs/blob/master/features/0031-discover-features/README.md#disclose-message-type) of the Discover Features protocol.

**Comment by dbluhm** [comment]
Merged with #12
